spring:
  application:
    name: manipulator-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      #       ddl-auto: create
      ddl-auto: update
    database: postgresql
server:
  port: 8081
